---
galaxy_info:
  author: Skander Taine <Skander.Tajine@skale-5.com>
  description: Installing and configuring rabbitMQ with mirrored cluster options
  company: Skale-5
  license: MIT
  min_ansible_version: 2.1
  platforms:
  - name: Debian
    versions:
    - all
  galaxy_tags:
    - rabbitmq
dependencies: []
