---
- name: stopping rabbitmq app
  command: rabbitmqctl stop_app
  become: true

- name: resetting rabbitmq app
  command: rabbitmqctl reset
  become: true

- name: Template rabbitmq configuration file
  template:
    src: rabbitmq.config.j2
    dest: /etc/rabbitmq/rabbitmq.config
  become: true

- name: starting rabbitmq app
  command: rabbitmqctl start_app
  become: true
  notify : "Restart RabbitMQ"
  
- name: force handler s execution , not waiting for normal sync points
  meta: flush_handlers
