---
- name: stopping rabbitmq app
  command: rabbitmqctl stop_app
  become: true

- name: resetting rabbitmq app
  command: rabbitmqctl reset
  become: true
  
- name: setting erlang cookie
  template:
    src: "erlang.cookie.j2"
    dest: /var/lib/rabbitmq/.erlang.cookie
    owner: "rabbitmq"
    group: "rabbitmq"
    mode: 0400
  become: true
  
- name: Template rabbitmq configuration file
  template:
    src: rabbitmq.config.j2
    dest: /etc/rabbitmq/rabbitmq.config
  become: true

- name: starting rabbitmq app
  command: rabbitmqctl start_app
  become: true

  
- name: Make sure a rabbitmq-server service is running
  systemd: state=started name=rabbimq-server
