---
- name: stop rabbitmq
  systemd: name=rabbitmq-server state=stopped

- name: setting erlang cookie
  template:
    src: "erlang.cookie.j2"
    dest: /var/lib/rabbitmq/.erlang.cookie
    owner: "rabbitmq"
    group: "rabbitmq"
    mode: 0400
  become: true
  
- name: start rabbitmq
  systemd: name=rabbitmq-server state=started

- name: force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers
