- name: rabbitmq_ha_config | setting up ha on queue(s)
  rabbitmq_policy:
    name: ha-all
    apply_to : all
    pattern: .*
    tags: 
      ha-mode: all
      ha-sync-mode: automatic
      max-length-bytes: 5368709120
    state: present
  run_once: true

