---
- name: Install RabbitMQ
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
    state: present
  with_items:
    - rabbitmq-server
    
- name: Start and enable rabbitmq
  systemd:
    name: rabbitmq-server
    state: started
    enabled: True
    daemon_reload: yes
